export const GET_PYALER_PROFILE = "GET_PLAYER_PROFILE";
export const GET_PLAYER_PROFILE_SUCCESS ="GET_PLAYER_PROFILE_SUCCESS";


export const FOLLOW_PLAYER = "FOLLOW_PLAYER";
export const FOLLOW_PLAYER_SUCCESS = "FOLLOW_PLAYER_SUCCESS";
export const FOLLOW_PLAYER_FAIL = "FOLLOW_PLAYER_FAIL";

export const UNFOLLOW_PLAYER = "UNFOLLOW_PLAYER";
export const UNFOLLOW_PLAYER_SUCCESS = "UNFOLLOW_PLAYER_SUCCESS";

export const BLOCK_PLAYER = "BLOCK_PLAYER";
export const BLOCK_PLAYER_SUCCESS = "BLOCK_PLAYER_SUCCESS";

export const UNBLOCK_PLAYER = "UNBLOCK_PLAYER";
export const UNBLOCK_PLAYER_SUCCESS = "UNBLOCK_PLAYER_SUCCESS";