export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCES";
export const USER_LOGIN_FAIL = "USER_LOGINFAIL";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USERREGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USERREGISTER_FAIL";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";


export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const GET_FOLLOWING_USERS = "GET_FOLLOWING_USERS";
export const GET_FOLLOWING_USERS_SUCCESS = "GET_FOLLOWING_USERS_SUCCESS";

export const PLAYER_UNFOLLOWED = "PLAYER_UNFOLLOWED";
export const PLAYER_FOLLOWED = "PLAYER_FOLLOWED";